language: python
# python 3.5 and later can do --install-binary for numpy
python:
- "2.7"
- "3.5"
- "3.6"

addons:
apt:
sources:
- ubuntu-toolchain-r-test
packages:

# command to install dependencies, numpy/scipy binaries
# are quicker and avoid lapack issues
install:
- pip install --only-binary=numpy numpy
- pip install .

# run pytest tests, build multinest first
script:
- pytest
